[package]
name = "tapes"
version = "0.2.0"
edition = "2024"
authors = ["Boog900"]
license = "MIT"
repository = "https://github.com/Cuprate/tapes"
description = "A minimal database for storing data in contigious tapes"

[dependencies]
slab = { version = "0.4" }
blake2 = { version = "0.10" }
borsh = { version = "1", features = ["derive"] }
parking_lot = { version = "0.12" }
bytemuck = { version = "1", features = ["derive"] }

[dev-dependencies]
tempfile = "3"
proptest = { version = "1" }
proptest-state-machine = { version = "0.6" }
